apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aura-ops

resources:
  - 00-namespace.yaml
  - 01-postgres.yaml
  - 02-clickhouse.yaml
  - 03-n8n.yaml
  - 04-aura-backend.yaml
  - 05-aura-frontend.yaml
  - 06-ingress.yaml
  - 07-cert-manager.yaml

# Desplegar todo de una vez:
#   kubectl apply -k ./kubernetes/
